{{- if .Values.instanceConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "linuxgsm-game.fullname" . }}-config
  labels:
    {{- include "linuxgsm-game.labels" . | nindent 4 }}
data:
  {{ .Values.game.shortname }}server.cfg: |
    {{- range $key, $value := .Values.instanceConfig }}
    {{ $key }}="{{ $value }}"
    {{- end }}
{{- end }}
