{{- if and .Values.secrets (not .Values.secretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "linuxgsm-game.secretName" . }}
  labels:
    {{- include "linuxgsm-game.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets-{{ .Values.game.shortname }}server.cfg: |
    {{- range $key, $value := .Values.secrets }}
    {{ $key }}="{{ $value }}"
    {{- end }}
{{- end }}
