{{- if and .Values.ports (not .Values.hostNetwork) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linuxgsm-game.fullname" . }}
  labels:
    {{- include "linuxgsm-game.labels" . | nindent 4 }}
spec:
  type: {{ if (include "linuxgsm-game.hasNodePort" .) }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    {{- include "linuxgsm-game.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.ports }}
    - name: {{ .name }}
      port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
{{- end }}
---
{{- if .Values.metricsExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "linuxgsm-game.fullname" . }}-metrics
  labels:
    {{- include "linuxgsm-game.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "linuxgsm-game.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsExporter.port }}
      targetPort: {{ .Values.metricsExporter.port }}
      protocol: TCP
{{- end }}
