{{- if not .Values.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim-server.secretName" . }}
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVER_PASS: {{ .Values.secrets.serverPassword | quote }}
{{- end }}
