apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim-server.fullname" . }}
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "valheim-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: game
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: UDP
      nodePort: {{ .Values.service.nodePorts.game }}
    - name: query
      port: {{ add .Values.server.port 1 }}
      targetPort: {{ add .Values.server.port 1 }}
      protocol: UDP
      nodePort: {{ .Values.service.nodePorts.query }}
    - name: rpc
      port: {{ add .Values.server.port 2 }}
      targetPort: {{ add .Values.server.port 2 }}
      protocol: UDP
      nodePort: {{ .Values.service.nodePorts.rpc }}
---
{{- if .Values.metricsExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "valheim-server.fullname" . }}-metrics
  labels:
    {{- include "valheim-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "valheim-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsExporter.port }}
      targetPort: {{ .Values.metricsExporter.port }}
      protocol: TCP
{{- end }}
