{{- if not .Values.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zomboid-server.secretName" . }}
  labels:
    {{- include "zomboid-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_PASS: {{ .Values.secrets.adminPassword | quote }}
  RCON_PASS: {{ .Values.secrets.rconPassword | quote }}
  SERVER_PASS: {{ .Values.secrets.serverPassword | quote }}
{{- end }}
