apiVersion: v1
kind: Service
metadata:
  name: {{ include "zomboid-server.fullname" . }}
  labels:
    {{- include "zomboid-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "zomboid-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: game
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
      protocol: UDP
      nodePort: {{ .Values.service.nodePorts.game }}
    - name: raknet
      port: {{ add .Values.server.port 1 }}
      targetPort: {{ add .Values.server.port 1 }}
      protocol: UDP
      nodePort: {{ .Values.service.nodePorts.raknet }}
    - name: rcon
      port: {{ .Values.server.rconPort }}
      targetPort: {{ .Values.server.rconPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePorts.rcon }}
---
{{- if .Values.statusMetrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zomboid-server.fullname" . }}-metrics
  labels:
    {{- include "zomboid-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "zomboid-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.statusMetrics.port }}
      targetPort: {{ .Values.statusMetrics.port }}
      protocol: TCP
{{- end }}
