alloy:
  configMap:
    create: true
    content: |
      discovery.kubernetes "pods" {
        role = "pod"
      }

      discovery.relabel "games_pods" {
        targets = discovery.kubernetes.pods.targets

        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          target_label  = "namespace"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          target_label  = "pod"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          target_label  = "container"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_node_name"]
          target_label  = "node"
        }
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          regex         = "games"
          action        = "keep"
        }
      }

      loki.source.kubernetes "games_pods" {
        targets    = discovery.relabel.games_pods.output
        forward_to = [loki.write.webserver_vm.receiver]
      }

      loki.write "webserver_vm" {
        endpoint {
          url = "http://loki.192.168.0.200.nip.io/loki/api/v1/push"
        }
        external_labels = {
          cluster = "k3s-gameservers",
        }
      }

  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

controller:
  type: deployment
  replicas: 1

rbac:
  create: true
