{{- if and .Values.alerts.enabled (not .Values.alerts.secretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enshrouded-server.fullname" . }}-discord
  labels:
    {{- include "enshrouded-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  DISCORD_WEBHOOK_URL: {{ .Values.alerts.discordWebhook | quote }}
{{- end }}
