apiVersion: v1
kind: Service
metadata:
  name: {{ include "enshrouded-server.fullname" . }}
  labels:
    {{- include "enshrouded-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "enshrouded-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: game
      port: {{ .Values.server.queryPort }}
      targetPort: {{ .Values.server.queryPort }}
      protocol: UDP
      nodePort: {{ .Values.service.nodePorts.game }}
---
{{- if .Values.statusMetrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "enshrouded-server.fullname" . }}-metrics
  labels:
    {{- include "enshrouded-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "enshrouded-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.statusMetrics.port }}
      targetPort: {{ .Values.statusMetrics.port }}
      protocol: TCP
{{- end }}
